
menu:
  主页: / || fa fa-home
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  时间轴: /archives/ || fas fa-archive
  # 留言板: /comment/ || fa fa-paper-plane
  关于: /about/ || fa fa-heart
highlight_theme: mac  # darker / pale night / light / ocean / mac / mac light /false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
code_word_wrap: false
# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 150
error_404:
  enable: true
  subtitle: 'Page Not Found'
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png

# social settings (社交圖標設置)
# formal:
#   icon: link || the description
# social settings (社交圖標設置)
# formal:
#   icon: link || the description
social:
   fab fa-github: https://github.com/lijinzedev || Github
   fas fa-envelope: mailto:2533755010@gmail.com || Email
algolia_search:
  enable: false
  hits:
    per_page: 6
# Math (數學)
# --------------------------------------
# About the per_page
# if you set it to true, it will load mathjax/katex script in each page (true 表示每一頁都加載js)
# if you set it to false, it will load mathjax/katex script according to your setting (add the 'mathjax: true' in page's front-matter)
# (false 需要時加載，須在使用的 Markdown Front-matter 加上 mathjax: true)

# MathJax
mathjax:
  enable: true
  per_page: true
# Favicon（網站圖標）
favicon: https://user-images.githubusercontent.com/41108332/105622748-e2c5b580-5e4e-11eb-95c9-b22cdfdd632b.png

# Avatar (頭像)
avatar:
  img: https://user-images.githubusercontent.com/41108332/105622748-e2c5b580-5e4e-11eb-95c9-b22cdfdd632b.png
  effect: false # 頭像會一直轉圈
aside:
  position: left # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/lijinzedev
  card_announcement:
    enable: true
    content: 万般皆下品,唯有读书高
medium_zoom:
  enable: true
related_post:
  enable: true
  limit: 6 #显示推荐文章数目
search:
  path: search.xml
  field: post
  content: true
# KaTeX
katex:
  enable: true
  per_page: false
  hide_scrollbar: true
  options:
        strict: false
# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # 如果没有查到内容相关内容显示
# If the banner of page not setting, it will show the top_img
# Loading Animation (加載動畫)
preloader: false
# Lazyload (圖片懶加載)
# https://github.com/verlok/lazyload
lazyload:
  enable: true
  post: /img/loading.gif